name: Sync Subfolder to Repo A

on:
  push:
    branches:
      - master
    paths:
      - 'this/is/subfolder/**'

jobs:
  push_subfolder_to_repo_a:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository B
        uses: actions/checkout@v4

      - name: Push 'this/is/subfolder' to Repository A
        uses: IMOitself/repo-missile@9a1c7667195cccbe0ebee95532c2ab1236c4fb2d
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_PAT }}
        with:
          source-files: 'this/is/subfolder/'
          destination-username: 'IMOaswell'
          destination-repository: 'A'
          destination-directory: 'this/is/subfolder'
          commit-email: 'IMOaswell@users.noreply.github.com'