# .github/workflows/push-to-repo-b.yml
name: Sync Subfolder to Repo A

on:
  push:
    branches:
      - master
    paths:
      - 'this/is/subfolder/**'

jobs:
  push_subfolder_to_repo_a:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout Repository A
        uses: actions/checkout@v4

      - name: Push 'this/is/subfolder' to Repository A
        uses: nkoppel/push-files-to-another-repository@v1.1.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_PAT }}
        with:
          source-files: 'this/is/subfolder/'
          destination-username: 'IMOaswell'
          destination-repository: 'A'
          destination-directory: 'this/is/subfolder'
          commit-email: 'IMOaswell@users.noreply.github.com'

